#!/usr/bin/env bash
#
# gen-packages.sh — regenerate packages.sh from the current system.
#
# Writes the two install arrays that bootstrap.sh sources:
#   PACMAN_PKGS = native/repo packages, AUR_PKGS = foreign/AUR packages.
# Source = your explicit, top-level (leaf) packages installed AFTER the
# provisioning cutoff (~/.local/state/deps-cutoff) — i.e. the same set `deps`
# shows. Run it whenever you want to snapshot what you've added. Safe to
# re-run: it fully overwrites packages.sh.

set -uo pipefail

here="$(dirname "$(realpath "$0")")"
out="$here/packages.sh"
cutoff_file="${XDG_STATE_HOME:-$HOME/.local/state}/deps-cutoff"
cutoff=""; [[ -f $cutoff_file ]] && cutoff=$(<"$cutoff_file")

# Explicit top-level (leaf) packages installed after the cutoff, by name.
mapfile -t names < <(
  join <(pacman -Qettq | sort) \
       <(awk '$3=="installed" && !s[$4]++ {t=$1; gsub(/[][]/,"",t); print $4, t}' /var/log/pacman.log | sort -k1,1) \
    | awk -v c="$cutoff" 'c=="" || substr($2,1,19) > substr(c,1,19) {print $1}' \
    | sort
)

# Split into native vs foreign. `pacman -Qqm` lists foreign (AUR) packages.
foreign=" $(pacman -Qqm | tr '\n' ' ') "
native_list=(); aur_list=()
for p in "${names[@]}"; do
  if [[ $foreign == *" $p "* ]]; then aur_list+=("$p"); else native_list+=("$p"); fi
done

{
  echo "#!/usr/bin/env bash"
  echo "# AUTO-GENERATED by gen-packages.sh on $(date +%Y-%m-%d) — do not hand-edit."
  echo "# Sourced by bootstrap.sh. Regenerate with: ./gen-packages.sh"
  echo
  echo "PACMAN_PKGS=("
  ((${#native_list[@]})) && printf '    %s\n' "${native_list[@]}"
  echo ")"
  echo
  echo "AUR_PKGS=("
  ((${#aur_list[@]})) && printf '    %s\n' "${aur_list[@]}"
  echo ")"
} > "$out"

echo "wrote $out — ${#native_list[@]} native, ${#aur_list[@]} AUR"
